# Generated by Django 5.2.5 on 2025-09-04 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('hod', 'HOD')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admission_mode', models.CharField(blank=True, choices=[('kcet', 'KCET'), ('comedk', 'COMED-K'), ('management', 'Management'), ('jee', 'JEE'), ('diploma', 'Diploma'), ('lateral', 'Lateral Entry'), ('other', 'Other')], max_length=20, null=True)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_type', models.CharField(choices=[('annual', 'Annual'), ('semester', 'Semester'), ('one_time', 'One-time')], default='annual', max_length=20)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('bulk', 'Bulk Assignment'), ('individual', 'Individual Assignment'), ('auto', 'Auto Assignment')], default='individual', max_length=20)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('overrides', models.JSONField(default=dict)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.feetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FeeTemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.feecomponent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.feetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='components',
            field=models.ManyToManyField(through='backend.FeeTemplateComponent', to='backend.feecomponent'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('annual', 'Annual Fee'), ('semester', 'Semester Fee'), ('one_time', 'One-time Fee')], default='annual', max_length=20)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('due_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.feeassignment')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='backend.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('dd', 'DD'), ('neft', 'NEFT')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.invoicecomponent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_allocations', to='backend.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.payment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dept', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('admission_mode', models.CharField(choices=[('kcet', 'KCET'), ('comedk', 'COMED-K'), ('management', 'Management'), ('jee', 'JEE'), ('diploma', 'Diploma'), ('lateral', 'Lateral Entry'), ('other', 'Other')], default='kcet', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('backlog', 'Backlog'), ('yearback', 'Yearback'), ('dropout', 'Dropout')], default='active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentprofile'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentprofile'),
        ),
        migrations.CreateModel(
            name='CustomFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.JSONField(default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.studentprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feeassignment',
            unique_together={('student', 'academic_year')},
        ),
    ]
